### ISSUE TITLE
Projetos Abertos para contribuição

### ISSUE THREAD

**Issue by lucaspdroz** [braziljs/ProjetosParaContribuir#1]
Liste seu projetos para serem ajudados!!
Todos os projetos podem ser adicionados, desde que sejam open-source!
```
**[Titulo](url)**
descrição do projeto
*Categoria*
*linguagem*
```
Categorias: *frontend, backend, IA, outros*

**Comment by lucaspdroz** [comment]
Liste seu projetos para serem ajudados!!
 Todos os projetos podem ser adicionados, desde que sejam open-source!
 ´´´
 # **[Titulo](url)**
descrição do projeto
Categoria
linguagem
´´´
Categorias: _frontend, backend, IA, outros_

**Comment by Maycon-Santos** [comment]
**[Transition Engine](https://github.com/Maycon-Santos/transition-engine)**
A simple animation engine
*Library*
*Typescript*

**Comment by manoelbjr** [comment]
**[FreeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp)**
Web Software Engineer Curriculum 
*Course*
*Javascript*

Gostaria de sugerir à comunidade BrazilJS o fork do FreeCodeCamp para trabalharmos na tradução para PT-BR, seguindo as  [Guidelines](https://forum.freecodecamp.org/t/guidelines-for-translating-free-code-camp-into-any-language/19111/5) de tradução projeto original.
